# Generated by Django 3.1.1 on 2020-10-06 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GradeAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='grade',
            name='A value is valid between 1-10',
        ),
    ]
