# Generated by Django 3.1.1 on 2020-10-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GradeAPI', '0002_auto_20201006_2145'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.CheckConstraint(check=models.Q(('value__gte', 1), ('value__lte', 10)), name='A value is valid between 1-10'),
        ),
    ]
